# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\VSCode_Project\python_project\fuzzProject\window_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import re
from Ui_dialog_v2 import Ui_Dialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setIconSize(QtCore.QSize(20, 20))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startFuzzBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startFuzzBtn.setGeometry(QtCore.QRect(510, 380, 93, 28))
        self.startFuzzBtn.setIconSize(QtCore.QSize(40, 40))
        self.startFuzzBtn.setObjectName("startFuzzBtn")
        self.CFileLoc = QtWidgets.QTextBrowser(self.centralwidget)
        self.CFileLoc.setEnabled(True)
        self.CFileLoc.setGeometry(QtCore.QRect(80, 80, 371, 31))
        self.CFileLoc.setObjectName("CFileLoc")
        self.chooseCBtn = QtWidgets.QPushButton(self.centralwidget)
        self.chooseCBtn.setGeometry(QtCore.QRect(510, 80, 93, 28))
        self.chooseCBtn.setAutoDefault(False)
        self.chooseCBtn.setDefault(False)
        self.chooseCBtn.setFlat(False)
        self.chooseCBtn.setObjectName("chooseCBtn")
        self.funcLevel = QtWidgets.QRadioButton(self.centralwidget)
        self.funcLevel.setGeometry(QtCore.QRect(510, 270, 115, 19))
        self.funcLevel.setChecked(True)
        self.funcLevel.setObjectName("funcLevel")
        self.branchLevel = QtWidgets.QRadioButton(self.centralwidget)
        self.branchLevel.setGeometry(QtCore.QRect(510, 310, 115, 19))
        self.branchLevel.setObjectName("branchLevel")
        self.instrOptions = QtWidgets.QLabel(self.centralwidget)
        self.instrOptions.setGeometry(QtCore.QRect(510, 230, 72, 15))
        self.instrOptions.setObjectName("instrOptions")
        self.status = QtWidgets.QTextBrowser(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(80, 380, 371, 31))
        self.status.setObjectName("status")
        self.targetSetInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.targetSetInfo.setGeometry(QtCore.QRect(80, 140, 371, 51))
        self.targetSetInfo.setObjectName("targetSetInfo")
        self.staticAnalysisBtn = QtWidgets.QPushButton(self.centralwidget)
        self.staticAnalysisBtn.setGeometry(QtCore.QRect(510, 150, 93, 28))
        self.staticAnalysisBtn.setObjectName("staticAnalysisBtn")
        self.seedInputText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.seedInputText.setGeometry(QtCore.QRect(80, 230, 371, 41))
        self.seedInputText.setObjectName("seedInputText")
        self.fuzzTime = QtWidgets.QSpinBox(self.centralwidget)
        self.fuzzTime.setGeometry(QtCore.QRect(250, 300, 101, 41))
        self.fuzzTime.setObjectName("fuzzTime")
        self.fuzzTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.fuzzTimeLabel.setGeometry(QtCore.QRect(160, 300, 91, 41))
        self.fuzzTimeLabel.setObjectName("fuzzTimeLabel")
        self.unit = QtWidgets.QComboBox(self.centralwidget)
        self.unit.setGeometry(QtCore.QRect(360, 300, 91, 41))
        self.unit.setObjectName("unit")
        self.unit.addItem("")
        self.unit.addItem("")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(320, 20, 91, 31))
        self.title.setLineWidth(1)
        self.title.setIndent(-1)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.startFuzzBtn.clicked.connect(self.popDialog)
        self.chooseCBtn.clicked.connect(self.chooseCFile)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startFuzzBtn.setText(_translate("MainWindow", "开始测试"))
        self.CFileLoc.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">C文件位置</p></body></html>"))
        self.chooseCBtn.setText(_translate("MainWindow", "选择C文件"))
        self.funcLevel.setText(_translate("MainWindow", "函数级"))
        self.branchLevel.setText(_translate("MainWindow", "分支级"))
        self.instrOptions.setText(_translate("MainWindow", "插桩粒度"))
        self.status.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">当前状态</p></body></html>"))
        self.targetSetInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">目标集信息</p></body></html>"))
        self.staticAnalysisBtn.setText(_translate("MainWindow", "静态分析"))
        # self.seedInputText.setPlainText(_translate("MainWindow", "在这里输入初始测试用例，也可以不输入"))
        self.seedInputText.setPlaceholderText("在这里输入初始测试用例，也可以不输入")
        self.fuzzTimeLabel.setText(_translate("MainWindow", "测试时间"))
        self.unit.setItemText(0, _translate("MainWindow", "分钟"))
        self.unit.setItemText(1, _translate("MainWindow", "小时"))
        self.title.setText(_translate("MainWindow", "简易测试工具"))
    
    def chooseCFile(self, Filepath):
        m = QtWidgets.QFileDialog.getOpenFileName(None,"choose file","C:/Users/Radon/Desktop/","c files (*.c)")
        path = re.sub("/",r"\\",m[0])
        self.CFileLoc.setText(path)

    def popDialog(self):
        source_loc = self.CFileLoc.toPlainText()
        # self.startFuzzBtn.setEnabled(False)
        # self.chooseCBtn.setEnabled(False)

        self.dialog = QtWidgets.QWidget()
        self.ui2 = Ui_Dialog()
        self.ui2.setupUi(self.dialog)
        self.dialog.show()
        self.ui2.startFuzz(source_loc,ui,self.ui2)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())